### ISSUE TITLE
Bug with panic (most likely caused by dereferencing a nil pointer)

### ISSUE THREAD

**Issue by katerinadenysova** [joonvena/robotframework-reporter-action#3]
This error started to appear yesterday and after some research on the internet that the info that I found could help to fix this issue: https://www.joeshaw.org/understanding-go-panic-output/ 
The error below is what I can see when running your reporter
```
open template.txt: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x574cdb]

goroutine 1 [running]:
html/template.(*Template).escape(0x0, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:97 +0x3b
html/template.(*Template).Execute(0x0, 0x810340, 0xc000380600, 0x743c40, 0xc0003805d0, 0x2d, 0x0)
	/usr/local/go/src/html/template/template.go:121 +0x2f
main.main()
	/build/main.go:251 +0xd1c
```

**Comment by joonvena** [comment]
Hi, i just released new version of this which now corrects the issue. Also updated the action itself. Highly suggest to changing to v1.0.
